name: Auto publish to static website

on:
  push:
    branches:
      - master

jobs:
  hugo-publish:
    name: publish content to static website
    runs-on: ubuntu-latest
    steps:
      - name: checkout blog repo
        uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install tencent cloud cloudbase
        shell: bash
        run: npm i -g @cloudbase/cli

      - name: publish blog to tencent static site
        working-directory: ./
        shell: bash
        run: |
          tcb login --apiKeyId ${{ secrets.QCLOUDAPIKEYID }} --apiKey ${{ secrets.QCLOUDAPIKEY }}
          rm -r ./.git
          tcb hosting deploy ./ -e ${{ secrets.QCLOUDENVID }}
